"""Platform definitions supported by this rule.

THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

Run the following command to generate this file from the '//:config.toml'.
$ bazel run //tools/platform_generator
"""

RUFF_PLATFORMS = {
    "aarch64-unknown-linux-gnu": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:aarch64",
        ],
        vender = "unknown",
        arch = "aarch64",
        os = "linux-gnu",
        ext = "tar.gz",
    ),
    "aarch64-apple-darwin": struct(
        compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:aarch64",
        ],
        vender = "apple",
        arch = "aarch64",
        os = "darwin",
        ext = "tar.gz",
    ),
    "x86_64-unknown-linux-gnu": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:x86_64",
        ],
        vender = "unknown",
        arch = "x86_64",
        os = "linux-gnu",
        ext = "tar.gz",
    ),
    "x86_64-apple-darwin": struct(
        compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:x86_64",
        ],
        vender = "apple",
        arch = "x86_64",
        os = "darwin",
        ext = "tar.gz",
    ),
}
