# Cut a release whenever a new tag is pushed to the repo.
name: Release
on:
  # Can be triggered from the tag.yaml workflow
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
    secrets:
      GCP_CREDENTIALS:
        required: true
      GCP_PROJECT_ID:
        required: true
  # Or, developers can manually push a tag from their clone
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
jobs:
  release:
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@0b644c3ee5c7cd9a7657f7e782b26a599d9b6d5c # 2025-01-23
    with:
      release_files: rules_ruff-*.tar.gz
      tag_name: ${{ inputs.tag_name }}
  upload-to-gcs:
    runs-on: ubuntu-latest
    steps:
      - name: Set TAG environment variable
        run: echo "TAG=${{ input.tag_name || github.ref_name }}" >> $GITHUB_ENV
      - name: Debug TAG
        run: |
          PREFIX="rules_ruff-${TAG:1}"
          ARCHIVE="rules_ruff-$TAG.tar.gz"

          echo "TAG=${TAG}"
          echo "PREFIX=${PREFIX}"
          echo "ARCHIVE=${ARCHIVE}"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${TAG}
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: ">= 524.0.0"
          project_id: "${{ secrets.GCP_PROJECT_ID }}"
      - name: Create variables and archive from tag
        run: |
          PREFIX="rules_ruff-${TAG:1}"
          ARCHIVE="rules_ruff-$TAG.tar.gz"

          # git archive (assuming proper .gitattributes)
          git archive --format=tar --prefix="${PREFIX}/" "$TAG" | gzip > "$ARCHIVE"

          # generate sha256 and save to env file
          SHA=$(shasum -a 256 "$ARCHIVE" | awk '{print $1}')
          echo "${SHA}" > "$ARCHIVE.sha256"
          echo "SHA256=${SHA}"
      - name: Upload Artifact to GCS
        run: |
          gsutil cp rules_ruff-*.tar.gz "gs://download-6e93fb8c/halaco/rules_ruff/${TAG}/"
          gsutil cp rules_ruff-*.tar.gz.sha256 "gs://download-6e93fb8c/halaco/rules_ruff/${TAG}/"
