# Cut a release whenever a new tag is pushed to the repo.
name: Release
on:
  # Can be triggered from the tag.yaml workflow
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
    secrets:
      GCP_CREDENTIALS:
        required: true
      GCP_PROJECT_ID:
        required: true
  # Or, developers can manually push a tag from their clone
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
jobs:
  release:
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@0b644c3ee5c7cd9a7657f7e782b26a599d9b6d5c # 2025-01-23
    with:
      release_files: rules_ruff-*.tar.gz
      tag_name: ${{ inputs.tag_name }}
  upload-to-gcs:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: ">= 524.0.0"
          project_id: "${{ secrets.GCP_PROJECT_ID }}"
      - name: Upload Artifact to GCS
        run: |
          gsutil cp rules_ruff-*.tar.gz "gs://download-6e93fb8c/halaco/rules_ruff/${{ inputs.tag_name }}/"
